---
###########################
###########################
## Pull request testing ##
###########################
###########################
name: Latest Pull Request

# Documentation:
# - Workflow: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# - SuperLinter: https://github.com/github/super-linter
# - Markdown linter: https://github.com/DavidAnson/markdownlint
# - Link validation: https://github.com/remarkjs/remark-validate-links

######################################################
# Start the job on a pull request to the main branch #
######################################################
on:
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  validate:
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0
      - run: cat ".github/super-linter.env" >> "$GITHUB_ENV"

      ################################
      # Run Linters against code base #
      ################################
      - name: Lint Code Base
        #
        # Use full version number to avoid cases when a next
        # released version is buggy
        # About slim image: https://github.com/github/super-linter#slim-image
        uses: github/super-linter/slim@v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true

      - name: Setup Node for Yarn
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Enable Corepack for Yarn
        run: corepack enable

      - name: Install dependencies
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Check internal links
        continue-on-error: true
        uses: borales/actions-yarn@v5
        with:
          cmd: test:links

      - name: Build site
        if: ${{ success() }}
        uses: borales/actions-yarn@v5
        with:
          cmd: build
